version: '3.8'

services:
  app:
    container_name: nodeApp
    restart: always
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/WesterosDB
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    command: >
     sh -c "npx prisma generate &&
            npx prisma migrate dev --name init &&
            npm run dev"
    
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: WesterosDB
    networks:
      - app-network
    logging:
      driver: "none"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge